include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false 
    implicit-dynamic: false 

  errors:
    missing_required_param: error
    missing_return: error
    dead_code: warning
    avoid_print: warning

linter:
  rules:
    - always_declare_return_types
    - annotate_overrides
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_empty_else
    - avoid_redundant_argument_values
    - avoid_relative_lib_imports
    - avoid_setters_without_getters
    - avoid_unnecessary_containers
    - avoid_void_async
    - camel_case_extensions
    - camel_case_types
    - cascade_invocations
    - constant_identifier_names
    - curly_braces_in_flow_control_structures
    - leading_newlines_in_multiline_strings
    - library_names
    - library_prefixes
    - non_constant_identifier_names
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_expression_function_bodies
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_relative_imports
    - prefer_single_quotes
    - require_trailing_commas
    - slash_for_doc_comments
    - unnecessary_brace_in_string_interps
    - use_function_type_syntax_for_parameters

